type(pokemon(bulbasaur), grass-poison).
type(pokemon(ivysaur), grass-poison).
type(pokemon(venusaur), grass-poison).
type(pokemon(charmander), fire).
type(pokemon(charmeleon), fire).
type(pokemon(charizard), fire-flying).
type(pokemon(squirtle), water).
type(pokemon(wartortle), water).
type(pokemon(blastoise), water).
type(pokemon(caterpie), bug).
type(pokemon(metapod), bug).
type(pokemon(butterfree), bug-flying).
type(pokemon(weedle), bug-poison).
type(pokemon(kakuna), bug-poison).
type(pokemon(beedrill), bug-poison).
type(pokemon(pidgey), normal-flying).
type(pokemon(pidgeotto), normal-flying).
type(pokemon(pidgeot), normal-flying).
type(pokemon(rattata), normal).
type(pokemon(raticate), normal).
type(pokemon(spearow), normal-flying).
type(pokemon(fearow), normal-flying).
type(pokemon(ekans), poison).
type(pokemon(arbok), poison).
type(pokemon(pikachu), electric).
type(pokemon(raichu), electric).
type(pokemon(sandshrew), ground).
type(pokemon(sandslash), ground).
type(pokemon(nidoran), poison).
type(pokemon(nidorina), poison).
type(pokemon(nidoqueen), poison-ground).
type(pokemon(nidorino), poison).
type(pokemon(nidoking), poison-ground).
type(pokemon(clefairy), normal).
type(pokemon(clefable), normal).
type(pokemon(vulpix), fire).
type(pokemon(ninetales), fire).
type(pokemon(jigglypuff), normal).
type(pokemon(wigglytuff), normal).
type(pokemon(zubat), poison-flying).
type(pokemon(golbat), poison-flying).
type(pokemon(oddish), grass-poison).
type(pokemon(gloom), grass-poison).
type(pokemon(vileplume), grass-poison).
type(pokemon(paras), bug-grass).
type(pokemon(parasect), bug-grass).
type(pokemon(venonat), bug-poison).
type(pokemon(venomoth), bug-poison).
type(pokemon(diglett), ground).
type(pokemon(dugtrio), ground).
type(pokemon(meowth), normal).
type(pokemon(persian), normal).
type(pokemon(psyduck), water).
type(pokemon(golduck), water).
type(pokemon(mankey), fighting).
type(pokemon(primeape), fighting).
type(pokemon(growlithe), fire).
type(pokemon(arcanine), fire).
type(pokemon(poliwag), water).
type(pokemon(poliwhirl), water).
type(pokemon(poliwrath), water-fighting).
type(pokemon(abra), psychic).
type(pokemon(kadabra), psychic).
type(pokemon(alakazam), psychic).
type(pokemon(machop), fighting).
type(pokemon(machoke), fighting).
type(pokemon(machamp), fighting).
type(pokemon(bellsprout), grass-poison).
type(pokemon(weepinbell), grass-poison).
type(pokemon(victreebel), grass-poison).
type(pokemon(tentacool), water-poison).
type(pokemon(tentacruel), water-poison).
type(pokemon(geodude), rock-ground).
type(pokemon(graveler), rock-ground).
type(pokemon(golem), rock-ground).
type(pokemon(ponyta), fire).
type(pokemon(rapidash), fire).
type(pokemon(slowpoke), water-psychic).
type(pokemon(slowbro), water-psychic).
type(pokemon(magnemite), electric-steel).
type(pokemon(magneton), electric-steel).
type(pokemon(farfetchd), normal-flying).
type(pokemon(doduo), normal-flying).
type(pokemon(dodrio), normal-flying).
type(pokemon(seel), water).
type(pokemon(dewgong), water-ice).
type(pokemon(grimer), poison).
type(pokemon(muk), poison).
type(pokemon(shellder), water).
type(pokemon(cloyster), water-ice).
type(pokemon(gastly), ghost-poison).
type(pokemon(haunter), ghost-poison).
type(pokemon(gengar), ghost-poison).
type(pokemon(onix), rock-ground).
type(pokemon(drowzee), psychic).
type(pokemon(hypno), psychic).
type(pokemon(krabby), water).
type(pokemon(kingler), water).
type(pokemon(voltorb), electric).
type(pokemon(electrode), electric).
type(pokemon(exeggcute), grass-psychic).
type(pokemon(exeggutor), grass-psychic).
type(pokemon(cubone), ground).
type(pokemon(marowak), ground).
type(pokemon(hitmonlee), fighting).
type(pokemon(hitmonchan), fighting).
type(pokemon(lickitung), normal).
type(pokemon(koffing), poison).
type(pokemon(weezing), poison).
type(pokemon(rhyhorn), ground-rock).
type(pokemon(rhydon), ground-rock).
type(pokemon(chansey), normal).
type(pokemon(tangela), grass).
type(pokemon(kangaskhan), normal).
type(pokemon(horsea), water).
type(pokemon(seadra), water).
type(pokemon(goldeen), water).
type(pokemon(seaking), water).
type(pokemon(staryu), water).
type(pokemon(starmie), water-psychic).
type(pokemon(mr-mime), psychic).
type(pokemon(scyther), bug-flying).
type(pokemon(jynx), ice-psychic).
type(pokemon(electabuzz), electric).
type(pokemon(magmar), fire).
type(pokemon(pinsir), bug).
type(pokemon(tauros), normal).
type(pokemon(magikarp), water).
type(pokemon(gyarados), water-flying).
type(pokemon(lapras), water-ice).
type(pokemon(ditto), normal).
type(pokemon(eevee), normal).
type(pokemon(vaporeon), water).
type(pokemon(jolteon), electric).
type(pokemon(flareon), fire).
type(pokemon(porygon), normal).
type(pokemon(omanyte), rock-water).
type(pokemon(omastar), rock-water).
type(pokemon(kabuto), rock-water).
type(pokemon(kabutops), rock-water).
type(pokemon(aerodactyl), rock-flying).
type(pokemon(snorlax), normal).
type(pokemon(articuno), ice-flying).
type(pokemon(zapdos), electric-flying).
type(pokemon(moltres), fire-flying).
type(pokemon(dratini), dragon).
type(pokemon(dragonair), dragon).
type(pokemon(dragonite), dragon-flying).
type(pokemon(mewtwo), psychic).
type(pokemon(mew), psychic).
type(pokemon(chikorita), grass).
type(pokemon(bayleef), grass).
type(pokemon(meganium), grass).
type(pokemon(cyndaquil), fire).
type(pokemon(quilava), fire).
type(pokemon(typhlosion), fire).
type(pokemon(totodile), water).
type(pokemon(croconaw), water).
type(pokemon(feraligatr), water).
type(pokemon(sentret), normal).
type(pokemon(furret), normal).
type(pokemon(hoothoot), normal-flying).
type(pokemon(noctowl), normal-flying).
type(pokemon(ledyba), bug-flying).
type(pokemon(ledian), bug-flying).
type(pokemon(spinarak), bug-poison).
type(pokemon(ariados), bug-poison).
type(pokemon(crobat), poison-flying).
type(pokemon(chinchou), water-electric).
type(pokemon(lanturn), water-electric).
type(pokemon(pichu), electric).
type(pokemon(cleffa), normal).
type(pokemon(igglybuff), normal).
type(pokemon(togepi), normal).
type(pokemon(togetic), normal-flying).
type(pokemon(natu), psychic-flying).
type(pokemon(xatu), psychic-flying).
type(pokemon(mareep), electric).
type(pokemon(flaaffy), electric).
type(pokemon(ampharos), electric).
type(pokemon(bellossom), grass).
type(pokemon(marill), water).
type(pokemon(azumarill), water).
type(pokemon(sudowoodo), rock).
type(pokemon(politoed), water).
type(pokemon(hoppip), grass-flying).
type(pokemon(skiploom), grass-flying).
type(pokemon(jumpluff), grass-flying).
type(pokemon(aipom), normal).
type(pokemon(sunkern), grass).
type(pokemon(sunflora), grass).
type(pokemon(yanma), bug-flying).
type(pokemon(wooper), water-ground).
type(pokemon(quagsire), water-ground).
type(pokemon(espeon), psychic).
type(pokemon(umbreon), dark).
type(pokemon(murkrow), dark-flying).
type(pokemon(slowking), water-psychic).
type(pokemon(misdreavus), ghost).
type(pokemon(unown), psychic).
type(pokemon(wobbuffet), psychic).
type(pokemon(girafarig), normal-psychic).
type(pokemon(pineco), bug).
type(pokemon(forretress), bug-steel).
type(pokemon(dunsparce), normal).
type(pokemon(gligar), ground-flying).
type(pokemon(steelix), steel-ground).
type(pokemon(snubbull), normal).
type(pokemon(granbull), normal).
type(pokemon(qwilfish), water-poison).
type(pokemon(scizor), bug-steel).
type(pokemon(shuckle), bug-rock).
type(pokemon(heracross), bug-fighting).
type(pokemon(sneasel), dark-ice).
type(pokemon(teddiursa), normal).
type(pokemon(ursaring), normal).
type(pokemon(slugma), fire).
type(pokemon(magcargo), fire-rock).
type(pokemon(swinub), ice-ground).
type(pokemon(piloswine), ice-ground).
type(pokemon(corsola), water-rock).
type(pokemon(remoraid), water).
type(pokemon(octillery), water).
type(pokemon(delibird), ice-flying).
type(pokemon(mantine), water-flying).
type(pokemon(skarmory), steel-flying).
type(pokemon(houndour), dark-fire).
type(pokemon(houndoom), dark-fire).
type(pokemon(kingdra), water-dragon).
type(pokemon(phanpy), ground).
type(pokemon(donphan), ground).
type(pokemon(porygon2), normal).
type(pokemon(stantler), normal).
type(pokemon(smeargle), normal).
type(pokemon(tyrogue), fighting).
type(pokemon(hitmontop), fighting).
type(pokemon(smoochum), ice-psychic).
type(pokemon(elekid), electric).
type(pokemon(magby), fire).
type(pokemon(miltank), normal).
type(pokemon(blissey), normal).
type(pokemon(raikou), electric).
type(pokemon(entei), fire).
type(pokemon(suicune), water).
type(pokemon(larvitar), rock-ground).
type(pokemon(pupitar), rock-ground).
type(pokemon(tyranitar), rock-dark).
type(pokemon(lugia), psychic-flying).
type(pokemon(ho-oh), fire-flying).
type(pokemon(celebi), psychic-grass).
type(pokemon(treecko), grass).
type(pokemon(grovyle), grass).
type(pokemon(sceptile), grass).
type(pokemon(torchic), fire).
type(pokemon(combusken), fire-fighting).
type(pokemon(blaziken), fire-fighting).
type(pokemon(mudkip), water).
type(pokemon(marshtomp), water-ground).
type(pokemon(swampert), water-ground).
type(pokemon(poochyena), dark).
type(pokemon(mightyena), dark).
type(pokemon(zigzagoon), normal).
type(pokemon(linoone), normal).
type(pokemon(wurmple), bug).
type(pokemon(silcoon), bug).
type(pokemon(beautifly), bug-flying).
type(pokemon(cascoon), bug).
type(pokemon(dustox), bug-poison).
type(pokemon(lotad), water-grass).
type(pokemon(lombre), water-grass).
type(pokemon(ludicolo), water-grass).
type(pokemon(seedot), grass).
type(pokemon(nuzleaf), grass-dark).
type(pokemon(shiftry), grass-dark).
type(pokemon(taillow), normal-flying).
type(pokemon(swellow), normal-flying).
type(pokemon(wingull), water-flying).
type(pokemon(pelipper), water-flying).
type(pokemon(ralts), psychic).
type(pokemon(kirlia), psychic).
type(pokemon(gardevoir), psychic).
type(pokemon(surskit), bug-water).
type(pokemon(masquerain), bug-flying).
type(pokemon(shroomish), grass).
type(pokemon(breloom), grass-fighting).
type(pokemon(slakoth), normal).
type(pokemon(vigoroth), normal).
type(pokemon(slaking), normal).
type(pokemon(nincada), bug-ground).
type(pokemon(ninjask), bug-flying).
type(pokemon(shedinja), bug-ghost).
type(pokemon(whismur), normal).
type(pokemon(loudred), normal).
type(pokemon(exploud), normal).
type(pokemon(makuhita), fighting).
type(pokemon(hariyama), fighting).
type(pokemon(azurill), normal).
type(pokemon(nosepass), rock).
type(pokemon(skitty), normal).
type(pokemon(delcatty), normal).
type(pokemon(sableye), dark-ghost).
type(pokemon(mawile), steel).
type(pokemon(aron), steel-rock).
type(pokemon(lairon), steel-rock).
type(pokemon(aggron), steel-rock).
type(pokemon(meditite), fighting-psychic).
type(pokemon(medicham), fighting-psychic).
type(pokemon(electrike), electric).
type(pokemon(manectric), electric).
type(pokemon(plusle), electric).
type(pokemon(minun), electric).
type(pokemon(volbeat), bug).
type(pokemon(illumise), bug).
type(pokemon(roselia), grass-poison).
type(pokemon(gulpin), poison).
type(pokemon(swalot), poison).
type(pokemon(carvanha), water-dark).
type(pokemon(sharpedo), water-dark).
type(pokemon(wailmer), water).
type(pokemon(wailord), water).
type(pokemon(numel), fire-ground).
type(pokemon(camerupt), fire-ground).
type(pokemon(torkoal), fire).
type(pokemon(spoink), psychic).
type(pokemon(grumpig), psychic).
type(pokemon(spinda), normal).
type(pokemon(trapinch), ground).
type(pokemon(vibrava), ground-dragon).
type(pokemon(flygon), ground-dragon).
type(pokemon(cacnea), grass).
type(pokemon(cacturne), grass-dark).
type(pokemon(swablu), normal-flying).
type(pokemon(altaria), dragon-flying).
type(pokemon(zangoose), normal).
type(pokemon(seviper), poison).
type(pokemon(lunatone), rock-psychic).
type(pokemon(solrock), rock-psychic).
type(pokemon(barboach), water-ground).
type(pokemon(whiscash), water-ground).
type(pokemon(corphish), water).
type(pokemon(crawdaunt), water-dark).
type(pokemon(baltoy), ground-psychic).
type(pokemon(claydol), ground-psychic).
type(pokemon(lileep), rock-grass).
type(pokemon(cradily), rock-grass).
type(pokemon(anorith), rock-bug).
type(pokemon(armaldo), rock-bug).
type(pokemon(feebas), water).
type(pokemon(milotic), water).
type(pokemon(castform), normal).
type(pokemon(kecleon), normal).
type(pokemon(shuppet), ghost).
type(pokemon(banette), ghost).
type(pokemon(duskull), ghost).
type(pokemon(dusclops), ghost).
type(pokemon(tropius), grass-flying).
type(pokemon(chimecho), psychic).
type(pokemon(absol), dark).
type(pokemon(wynaut), psychic).
type(pokemon(snorunt), ice).
type(pokemon(glalie), ice).
type(pokemon(spheal), ice-water).
type(pokemon(sealeo), ice-water).
type(pokemon(walrein), ice-water).
type(pokemon(clamperl), water).
type(pokemon(huntail), water).
type(pokemon(gorebyss), water).
type(pokemon(relicanth), water-rock).
type(pokemon(luvdisc), water).
type(pokemon(bagon), dragon).
type(pokemon(shelgon), dragon).
type(pokemon(salamence), dragon-flying).
type(pokemon(beldum), steel-psychic).
type(pokemon(metang), steel-psychic).
type(pokemon(metagross), steel-psychic).
type(pokemon(regirock), rock).
type(pokemon(regice), ice).
type(pokemon(registeel), steel).
type(pokemon(latias), dragon-psychic).
type(pokemon(latios), dragon-psychic).
type(pokemon(kyogre), water).
type(pokemon(groudon), ground).
type(pokemon(rayquaza), dragon-flying).
type(pokemon(jirachi), steel-psychic).
type(pokemon(deoxys), psychic).
type(pokemon(turtwig), grass).
type(pokemon(grotle), grass).
type(pokemon(torterra), grass-ground).
type(pokemon(chimchar), fire).
type(pokemon(monferno), fire-fighting).
type(pokemon(infernape), fire-fighting).
type(pokemon(piplup), water).
type(pokemon(prinplup), water).
type(pokemon(empoleon), water-steel).
type(pokemon(starly), normal-flying).
type(pokemon(staravia), normal-flying).
type(pokemon(staraptor), normal-flying).
type(pokemon(bidoof), normal).
type(pokemon(bibarel), normal-water).
type(pokemon(kricketot), bug).
type(pokemon(kricketune), bug).
type(pokemon(shinx), electric).
type(pokemon(luxio), electric).
type(pokemon(luxray), electric).
type(pokemon(budew), grass-poison).
type(pokemon(roserade), grass-poison).
type(pokemon(cranidos), rock).
type(pokemon(rampardos), rock).
type(pokemon(shieldon), rock-steel).
type(pokemon(bastiodon), rock-steel).
type(pokemon(burmy), bug).
type(pokemon(wormadam), bug-grass).
type(pokemon(mothim), bug-flying).
type(pokemon(combee), bug-flying).
type(pokemon(vespiquen), bug-flying).
type(pokemon(pachirisu), electric).
type(pokemon(buizel), water).
type(pokemon(floatzel), water).
type(pokemon(cherubi), grass).
type(pokemon(cherrim), grass).
type(pokemon(shellos), water).
type(pokemon(gastrodon), water-ground).
type(pokemon(ambipom), normal).
type(pokemon(drifloon), ghost-flying).
type(pokemon(drifblim), ghost-flying).
type(pokemon(buneary), normal).
type(pokemon(lopunny), normal).
type(pokemon(mismagius), ghost).
type(pokemon(honchkrow), dark-flying).
type(pokemon(glameow), normal).
type(pokemon(purugly), normal).
type(pokemon(chingling), psychic).
type(pokemon(stunky), poison-dark).
type(pokemon(skuntank), poison-dark).
type(pokemon(bronzor), steel-psychic).
type(pokemon(bronzong), steel-psychic).
type(pokemon(bonsly), rock).
type(pokemon(mime-jr), psychic).
type(pokemon(happiny), normal).
type(pokemon(chatot), normal-flying).
type(pokemon(spiritomb), ghost-dark).
type(pokemon(gible), dragon-ground).
type(pokemon(gabite), dragon-ground).
type(pokemon(garchomp), dragon-ground).
type(pokemon(munchlax), normal).
type(pokemon(riolu), fighting).
type(pokemon(lucario), fighting-steel).
type(pokemon(hippopotas), ground).
type(pokemon(hippowdon), ground).
type(pokemon(skorupi), poison-bug).
type(pokemon(drapion), poison-dark).
type(pokemon(croagunk), poison-fighting).
type(pokemon(toxicroak), poison-fighting).
type(pokemon(carnivine), grass).
type(pokemon(finneon), water).
type(pokemon(lumineon), water).
type(pokemon(mantyke), water-flying).
type(pokemon(snover), ice-grass).
type(pokemon(abomasnow), ice-grass).
type(pokemon(weavile), dark-ice).
type(pokemon(magnezone), electric-steel).
type(pokemon(lickilicky), normal).
type(pokemon(rhyperior), ground-rock).
type(pokemon(tangrowth), grass).
type(pokemon(electivire), electric).
type(pokemon(magmortar), fire).
type(pokemon(togekiss), normal-flying).
type(pokemon(yanmega), bug-flying).
type(pokemon(leafeon), grass).
type(pokemon(glaceon), ice).
type(pokemon(gliscor), ground-flying).
type(pokemon(mamoswine), ice-ground).
type(pokemon(porygon-z), normal).
type(pokemon(gallade), psychic-fighting).
type(pokemon(probopass), rock-steel).
type(pokemon(dusknoir), ghost).
type(pokemon(froslass), ice-ghost).
type(pokemon(rotom), electric-ghost).
type(pokemon(uxie), psychic).
type(pokemon(mesprit), psychic).
type(pokemon(azelf), psychic).
type(pokemon(dialga), steel-dragon).
type(pokemon(palkia), water-dragon).
type(pokemon(heatran), fire-steel).
type(pokemon(regigigas), normal).
type(pokemon(giratina), ghost-dragon).
type(pokemon(cresselia), psychic).
type(pokemon(phione), water).
type(pokemon(manaphy), water).
type(pokemon(darkrai), dark).
type(pokemon(shaymin), grass).
type(pokemon(arceus), normal).
type(pokemon(victini), psychic-fire).
type(pokemon(snivy), grass).
type(pokemon(servine), grass).
type(pokemon(serperior), grass).
type(pokemon(tepig), fire).
type(pokemon(pignite), fire-fighting).
type(pokemon(emboar), fire-fighting).
type(pokemon(oshawott), water).
type(pokemon(dewott), water).
type(pokemon(samurott), water).
type(pokemon(patrat), normal).
type(pokemon(watchog), normal).
type(pokemon(lillipup), normal).
type(pokemon(herdier), normal).
type(pokemon(stoutland), normal).
type(pokemon(purrloin), dark).
type(pokemon(liepard), dark).
type(pokemon(pansage), grass).
type(pokemon(simisage), grass).
type(pokemon(pansear), fire).
type(pokemon(simisear), fire).
type(pokemon(panpour), water).
type(pokemon(simipour), water).
type(pokemon(munna), psychic).
type(pokemon(musharna), psychic).
type(pokemon(pidove), normal-flying).
type(pokemon(tranquill), normal-flying).
type(pokemon(unfezant), normal-flying).
type(pokemon(blitzle), electric).
type(pokemon(zebstrika), electric).
type(pokemon(roggenrola), rock).
type(pokemon(boldore), rock).
type(pokemon(gigalith), rock).
type(pokemon(woobat), psychic-flying).
type(pokemon(swoobat), psychic-flying).
type(pokemon(drilbur), ground).
type(pokemon(excadrill), ground-steel).
type(pokemon(audino), normal).
type(pokemon(timburr), fighting).
type(pokemon(gurdurr), fighting).
type(pokemon(conkeldurr), fighting).
type(pokemon(tympole), water).
type(pokemon(palpitoad), water-ground).
type(pokemon(seismitoad), water-ground).
type(pokemon(throh), fighting).
type(pokemon(sawk), fighting).
type(pokemon(sewaddle), bug-grass).
type(pokemon(swadloon), bug-grass).
type(pokemon(leavanny), bug-grass).
type(pokemon(venipede), bug-poison).
type(pokemon(whirlipede), bug-poison).
type(pokemon(scolipede), bug-poison).
type(pokemon(cottonee), grass).
type(pokemon(whimsicott), grass).
type(pokemon(petilil), grass).
type(pokemon(lilligant), grass).
type(pokemon(basculin), water).
type(pokemon(sandile), ground-dark).
type(pokemon(krokorok), ground-dark).
type(pokemon(krookodile), ground-dark).
type(pokemon(darumaka), fire).
type(pokemon(darmanitan), fire).
type(pokemon(maractus), grass).
type(pokemon(dwebble), bug-rock).
type(pokemon(crustle), bug-rock).
type(pokemon(scraggy), dark-fighting).
type(pokemon(scrafty), dark-fighting).
type(pokemon(sigilyph), psychic-flying).
type(pokemon(yamask), ghost).
type(pokemon(cofagrigus), ghost).
type(pokemon(tirtouga), water-rock).
type(pokemon(carracosta), water-rock).
type(pokemon(archen), rock-flying).
type(pokemon(archeops), rock-flying).
type(pokemon(trubbish), poison).
type(pokemon(garbodor), poison).
type(pokemon(zorua), dark).
type(pokemon(zoroark), dark).
type(pokemon(minccino), normal).
type(pokemon(ciccino), normal).
type(pokemon(gothita), psychic).
type(pokemon(gothorita), psychic).
type(pokemon(gothitelle), psychic).
type(pokemon(solosis), psychic).
type(pokemon(duosion), psychic).
type(pokemon(reuniclus), psychic).
type(pokemon(ducklett), water-flying).
type(pokemon(swanna), water-flying).
type(pokemon(vanillite), ice).
type(pokemon(vanillish), ice).
type(pokemon(vanilluxe), ice).
type(pokemon(deerling), normal-grass).
type(pokemon(sawsbuck), normal-grass).
type(pokemon(emolga), electric-flying).
type(pokemon(karrablast), bug).
type(pokemon(escavalier), bug-steel).
type(pokemon(foongus), grass-poison).
type(pokemon(amoonguss), grass-poison).
type(pokemon(frillish), water-ghost).
type(pokemon(jellicent), water-ghost).
type(pokemon(alomomola), water).
type(pokemon(joltik), bug-electric).
type(pokemon(galvantula), bug-electric).
type(pokemon(ferroseed), grass-steel).
type(pokemon(ferrothorn), grass-steel).
type(pokemon(klink), steel).
type(pokemon(klang), steel).
type(pokemon(klinklang), steel).
type(pokemon(tynamo), electric).
type(pokemon(eelektrik), electric).
type(pokemon(eelektross), electric).
type(pokemon(elgyem), psychic).
type(pokemon(beheeyem), psychic).
type(pokemon(litwick), ghost-fire).
type(pokemon(lampent), ghost-fire).
type(pokemon(chandelure), ghost-fire).
type(pokemon(axew), dragon).
type(pokemon(fraxure), dragon).
type(pokemon(haxorus), dragon).
type(pokemon(cubchoo), ice).
type(pokemon(beartic), ice).
type(pokemon(cryogonal), ice).
type(pokemon(shelmet), bug).
type(pokemon(accelgor), bug).
type(pokemon(stunfisk), ground-electric).
type(pokemon(mienfoo), fighting).
type(pokemon(mienshao), fighting).
type(pokemon(druddigon), dragon).
type(pokemon(golett), ground-ghost).
type(pokemon(golurk), ground-ghost).
type(pokemon(pawniard), dark-steel).
type(pokemon(bisharp), dark-steel).
type(pokemon(bouffalant), normal).
type(pokemon(rufflet), normal-flying).
type(pokemon(braviary), normal-flying).
type(pokemon(vullaby), dark-flying).
type(pokemon(mandibuzz), dark-flying).
type(pokemon(heatmor), fire).
type(pokemon(durant), bug-steel).
type(pokemon(deino), dark-dragon).
type(pokemon(zweilous), dark-dragon).
type(pokemon(hydreigon), dark-dragon).
type(pokemon(larvesta), bug-fire).
type(pokemon(volcarona), bug-fire).
type(pokemon(cobalion), steel-fighting).
type(pokemon(terrakion), rock-fighting).
type(pokemon(virizion), grass-fighting).
type(pokemon(tornadus), flying).
type(pokemon(thundurus), electric-flying).
type(pokemon(reshiram), dragon-fire).
type(pokemon(zekrom), dragon-electric).
type(pokemon(landorus), ground-flying).
type(pokemon(kyurem), dragon-ice).
type(pokemon(keldeo), water-fighting).
type(pokemon(meloetta), normal-psychic).
type(pokemon(genesect), bug-steel).
