type(pokemon(bulbasaur), grass_poison).
type(pokemon(ivysaur), grass_poison).
type(pokemon(venusaur), grass_poison).
type(pokemon(charmander), fire).
type(pokemon(charmeleon), fire).
type(pokemon(charizard), fire_flying).
type(pokemon(squirtle), water).
type(pokemon(wartortle), water).
type(pokemon(blastoise), water).
type(pokemon(caterpie), bug).
type(pokemon(metapod), bug).
type(pokemon(butterfree), bug_flying).
type(pokemon(weedle), bug_poison).
type(pokemon(kakuna), bug_poison).
type(pokemon(beedrill), bug_poison).
type(pokemon(pidgey), normal_flying).
type(pokemon(pidgeotto), normal_flying).
type(pokemon(pidgeot), normal_flying).
type(pokemon(rattata), normal).
type(pokemon(raticate), normal).
type(pokemon(spearow), normal_flying).
type(pokemon(fearow), normal_flying).
type(pokemon(ekans), poison).
type(pokemon(arbok), poison).
type(pokemon(pikachu), electric).
type(pokemon(raichu), electric).
type(pokemon(sandshrew), ground).
type(pokemon(sandslash), ground).
type(pokemon(nidoran), poison).
type(pokemon(nidorina), poison).
type(pokemon(nidoqueen), poison_ground).
type(pokemon(nidorino), poison).
type(pokemon(nidoking), poison_ground).
type(pokemon(clefairy), normal).
type(pokemon(clefable), normal).
type(pokemon(vulpix), fire).
type(pokemon(ninetales), fire).
type(pokemon(jigglypuff), normal).
type(pokemon(wigglytuff), normal).
type(pokemon(zubat), poison_flying).
type(pokemon(golbat), poison_flying).
type(pokemon(oddish), grass_poison).
type(pokemon(gloom), grass_poison).
type(pokemon(vileplume), grass_poison).
type(pokemon(paras), bug_grass).
type(pokemon(parasect), bug_grass).
type(pokemon(venonat), bug_poison).
type(pokemon(venomoth), bug_poison).
type(pokemon(diglett), ground).
type(pokemon(dugtrio), ground).
type(pokemon(meowth), normal).
type(pokemon(persian), normal).
type(pokemon(psyduck), water).
type(pokemon(golduck), water).
type(pokemon(mankey), fighting).
type(pokemon(primeape), fighting).
type(pokemon(growlithe), fire).
type(pokemon(arcanine), fire).
type(pokemon(poliwag), water).
type(pokemon(poliwhirl), water).
type(pokemon(poliwrath), water_fighting).
type(pokemon(abra), psychic).
type(pokemon(kadabra), psychic).
type(pokemon(alakazam), psychic).
type(pokemon(machop), fighting).
type(pokemon(machoke), fighting).
type(pokemon(machamp), fighting).
type(pokemon(bellsprout), grass_poison).
type(pokemon(weepinbell), grass_poison).
type(pokemon(victreebel), grass_poison).
type(pokemon(tentacool), water_poison).
type(pokemon(tentacruel), water_poison).
type(pokemon(geodude), rock_ground).
type(pokemon(graveler), rock_ground).
type(pokemon(golem), rock_ground).
type(pokemon(ponyta), fire).
type(pokemon(rapidash), fire).
type(pokemon(slowpoke), water_psychic).
type(pokemon(slowbro), water_psychic).
type(pokemon(magnemite), electric_steel).
type(pokemon(magneton), electric_steel).
type(pokemon(farfetchd), normal_flying).
type(pokemon(doduo), normal_flying).
type(pokemon(dodrio), normal_flying).
type(pokemon(seel), water).
type(pokemon(dewgong), water_ice).
type(pokemon(grimer), poison).
type(pokemon(muk), poison).
type(pokemon(shellder), water).
type(pokemon(cloyster), water_ice).
type(pokemon(gastly), ghost_poison).
type(pokemon(haunter), ghost_poison).
type(pokemon(gengar), ghost_poison).
type(pokemon(onix), rock_ground).
type(pokemon(drowzee), psychic).
type(pokemon(hypno), psychic).
type(pokemon(krabby), water).
type(pokemon(kingler), water).
type(pokemon(voltorb), electric).
type(pokemon(electrode), electric).
type(pokemon(exeggcute), grass_psychic).
type(pokemon(exeggutor), grass_psychic).
type(pokemon(cubone), ground).
type(pokemon(marowak), ground).
type(pokemon(hitmonlee), fighting).
type(pokemon(hitmonchan), fighting).
type(pokemon(lickitung), normal).
type(pokemon(koffing), poison).
type(pokemon(weezing), poison).
type(pokemon(rhyhorn), ground_rock).
type(pokemon(rhydon), ground_rock).
type(pokemon(chansey), normal).
type(pokemon(tangela), grass).
type(pokemon(kangaskhan), normal).
type(pokemon(horsea), water).
type(pokemon(seadra), water).
type(pokemon(goldeen), water).
type(pokemon(seaking), water).
type(pokemon(staryu), water).
type(pokemon(starmie), water_psychic).
type(pokemon(mr_mime), psychic).
type(pokemon(scyther), bug_flying).
type(pokemon(jynx), ice_psychic).
type(pokemon(electabuzz), electric).
type(pokemon(magmar), fire).
type(pokemon(pinsir), bug).
type(pokemon(tauros), normal).
type(pokemon(magikarp), water).
type(pokemon(gyarados), water_flying).
type(pokemon(lapras), water_ice).
type(pokemon(ditto), normal).
type(pokemon(eevee), normal).
type(pokemon(vaporeon), water).
type(pokemon(jolteon), electric).
type(pokemon(flareon), fire).
type(pokemon(porygon), normal).
type(pokemon(omanyte), rock_water).
type(pokemon(omastar), rock_water).
type(pokemon(kabuto), rock_water).
type(pokemon(kabutops), rock_water).
type(pokemon(aerodactyl), rock_flying).
type(pokemon(snorlax), normal).
type(pokemon(articuno), ice_flying).
type(pokemon(zapdos), electric_flying).
type(pokemon(moltres), fire_flying).
type(pokemon(dratini), dragon).
type(pokemon(dragonair), dragon).
type(pokemon(dragonite), dragon_flying).
type(pokemon(mewtwo), psychic).
type(pokemon(mew), psychic).
type(pokemon(chikorita), grass).
type(pokemon(bayleef), grass).
type(pokemon(meganium), grass).
type(pokemon(cyndaquil), fire).
type(pokemon(quilava), fire).
type(pokemon(typhlosion), fire).
type(pokemon(totodile), water).
type(pokemon(croconaw), water).
type(pokemon(feraligatr), water).
type(pokemon(sentret), normal).
type(pokemon(furret), normal).
type(pokemon(hoothoot), normal_flying).
type(pokemon(noctowl), normal_flying).
type(pokemon(ledyba), bug_flying).
type(pokemon(ledian), bug_flying).
type(pokemon(spinarak), bug_poison).
type(pokemon(ariados), bug_poison).
type(pokemon(crobat), poison_flying).
type(pokemon(chinchou), water_electric).
type(pokemon(lanturn), water_electric).
type(pokemon(pichu), electric).
type(pokemon(cleffa), normal).
type(pokemon(igglybuff), normal).
type(pokemon(togepi), normal).
type(pokemon(togetic), normal_flying).
type(pokemon(natu), psychic_flying).
type(pokemon(xatu), psychic_flying).
type(pokemon(mareep), electric).
type(pokemon(flaaffy), electric).
type(pokemon(ampharos), electric).
type(pokemon(bellossom), grass).
type(pokemon(marill), water).
type(pokemon(azumarill), water).
type(pokemon(sudowoodo), rock).
type(pokemon(politoed), water).
type(pokemon(hoppip), grass_flying).
type(pokemon(skiploom), grass_flying).
type(pokemon(jumpluff), grass_flying).
type(pokemon(aipom), normal).
type(pokemon(sunkern), grass).
type(pokemon(sunflora), grass).
type(pokemon(yanma), bug_flying).
type(pokemon(wooper), water_ground).
type(pokemon(quagsire), water_ground).
type(pokemon(espeon), psychic).
type(pokemon(umbreon), dark).
type(pokemon(murkrow), dark_flying).
type(pokemon(slowking), water_psychic).
type(pokemon(misdreavus), ghost).
type(pokemon(unown), psychic).
type(pokemon(wobbuffet), psychic).
type(pokemon(girafarig), normal_psychic).
type(pokemon(pineco), bug).
type(pokemon(forretress), bug_steel).
type(pokemon(dunsparce), normal).
type(pokemon(gligar), ground_flying).
type(pokemon(steelix), steel_ground).
type(pokemon(snubbull), normal).
type(pokemon(granbull), normal).
type(pokemon(qwilfish), water_poison).
type(pokemon(scizor), bug_steel).
type(pokemon(shuckle), bug_rock).
type(pokemon(heracross), bug_fighting).
type(pokemon(sneasel), dark_ice).
type(pokemon(teddiursa), normal).
type(pokemon(ursaring), normal).
type(pokemon(slugma), fire).
type(pokemon(magcargo), fire_rock).
type(pokemon(swinub), ice_ground).
type(pokemon(piloswine), ice_ground).
type(pokemon(corsola), water_rock).
type(pokemon(remoraid), water).
type(pokemon(octillery), water).
type(pokemon(delibird), ice_flying).
type(pokemon(mantine), water_flying).
type(pokemon(skarmory), steel_flying).
type(pokemon(houndour), dark_fire).
type(pokemon(houndoom), dark_fire).
type(pokemon(kingdra), water_dragon).
type(pokemon(phanpy), ground).
type(pokemon(donphan), ground).
type(pokemon(porygon2), normal).
type(pokemon(stantler), normal).
type(pokemon(smeargle), normal).
type(pokemon(tyrogue), fighting).
type(pokemon(hitmontop), fighting).
type(pokemon(smoochum), ice_psychic).
type(pokemon(elekid), electric).
type(pokemon(magby), fire).
type(pokemon(miltank), normal).
type(pokemon(blissey), normal).
type(pokemon(raikou), electric).
type(pokemon(entei), fire).
type(pokemon(suicune), water).
type(pokemon(larvitar), rock_ground).
type(pokemon(pupitar), rock_ground).
type(pokemon(tyranitar), rock_dark).
type(pokemon(lugia), psychic_flying).
type(pokemon(ho_oh), fire_flying).
type(pokemon(celebi), psychic_grass).
type(pokemon(treecko), grass).
type(pokemon(grovyle), grass).
type(pokemon(sceptile), grass).
type(pokemon(torchic), fire).
type(pokemon(combusken), fire_fighting).
type(pokemon(blaziken), fire_fighting).
type(pokemon(mudkip), water).
type(pokemon(marshtomp), water_ground).
type(pokemon(swampert), water_ground).
type(pokemon(poochyena), dark).
type(pokemon(mightyena), dark).
type(pokemon(zigzagoon), normal).
type(pokemon(linoone), normal).
type(pokemon(wurmple), bug).
type(pokemon(silcoon), bug).
type(pokemon(beautifly), bug_flying).
type(pokemon(cascoon), bug).
type(pokemon(dustox), bug_poison).
type(pokemon(lotad), water_grass).
type(pokemon(lombre), water_grass).
type(pokemon(ludicolo), water_grass).
type(pokemon(seedot), grass).
type(pokemon(nuzleaf), grass_dark).
type(pokemon(shiftry), grass_dark).
type(pokemon(taillow), normal_flying).
type(pokemon(swellow), normal_flying).
type(pokemon(wingull), water_flying).
type(pokemon(pelipper), water_flying).
type(pokemon(ralts), psychic).
type(pokemon(kirlia), psychic).
type(pokemon(gardevoir), psychic).
type(pokemon(surskit), bug_water).
type(pokemon(masquerain), bug_flying).
type(pokemon(shroomish), grass).
type(pokemon(breloom), grass_fighting).
type(pokemon(slakoth), normal).
type(pokemon(vigoroth), normal).
type(pokemon(slaking), normal).
type(pokemon(nincada), bug_ground).
type(pokemon(ninjask), bug_flying).
type(pokemon(shedinja), bug_ghost).
type(pokemon(whismur), normal).
type(pokemon(loudred), normal).
type(pokemon(exploud), normal).
type(pokemon(makuhita), fighting).
type(pokemon(hariyama), fighting).
type(pokemon(azurill), normal).
type(pokemon(nosepass), rock).
type(pokemon(skitty), normal).
type(pokemon(delcatty), normal).
type(pokemon(sableye), dark_ghost).
type(pokemon(mawile), steel).
type(pokemon(aron), steel_rock).
type(pokemon(lairon), steel_rock).
type(pokemon(aggron), steel_rock).
type(pokemon(meditite), fighting_psychic).
type(pokemon(medicham), fighting_psychic).
type(pokemon(electrike), electric).
type(pokemon(manectric), electric).
type(pokemon(plusle), electric).
type(pokemon(minun), electric).
type(pokemon(volbeat), bug).
type(pokemon(illumise), bug).
type(pokemon(roselia), grass_poison).
type(pokemon(gulpin), poison).
type(pokemon(swalot), poison).
type(pokemon(carvanha), water_dark).
type(pokemon(sharpedo), water_dark).
type(pokemon(wailmer), water).
type(pokemon(wailord), water).
type(pokemon(numel), fire_ground).
type(pokemon(camerupt), fire_ground).
type(pokemon(torkoal), fire).
type(pokemon(spoink), psychic).
type(pokemon(grumpig), psychic).
type(pokemon(spinda), normal).
type(pokemon(trapinch), ground).
type(pokemon(vibrava), ground_dragon).
type(pokemon(flygon), ground_dragon).
type(pokemon(cacnea), grass).
type(pokemon(cacturne), grass_dark).
type(pokemon(swablu), normal_flying).
type(pokemon(altaria), dragon_flying).
type(pokemon(zangoose), normal).
type(pokemon(seviper), poison).
type(pokemon(lunatone), rock_psychic).
type(pokemon(solrock), rock_psychic).
type(pokemon(barboach), water_ground).
type(pokemon(whiscash), water_ground).
type(pokemon(corphish), water).
type(pokemon(crawdaunt), water_dark).
type(pokemon(baltoy), ground_psychic).
type(pokemon(claydol), ground_psychic).
type(pokemon(lileep), rock_grass).
type(pokemon(cradily), rock_grass).
type(pokemon(anorith), rock_bug).
type(pokemon(armaldo), rock_bug).
type(pokemon(feebas), water).
type(pokemon(milotic), water).
type(pokemon(castform), normal).
type(pokemon(kecleon), normal).
type(pokemon(shuppet), ghost).
type(pokemon(banette), ghost).
type(pokemon(duskull), ghost).
type(pokemon(dusclops), ghost).
type(pokemon(tropius), grass_flying).
type(pokemon(chimecho), psychic).
type(pokemon(absol), dark).
type(pokemon(wynaut), psychic).
type(pokemon(snorunt), ice).
type(pokemon(glalie), ice).
type(pokemon(spheal), ice_water).
type(pokemon(sealeo), ice_water).
type(pokemon(walrein), ice_water).
type(pokemon(clamperl), water).
type(pokemon(huntail), water).
type(pokemon(gorebyss), water).
type(pokemon(relicanth), water_rock).
type(pokemon(luvdisc), water).
type(pokemon(bagon), dragon).
type(pokemon(shelgon), dragon).
type(pokemon(salamence), dragon_flying).
type(pokemon(beldum), steel_psychic).
type(pokemon(metang), steel_psychic).
type(pokemon(metagross), steel_psychic).
type(pokemon(regirock), rock).
type(pokemon(regice), ice).
type(pokemon(registeel), steel).
type(pokemon(latias), dragon_psychic).
type(pokemon(latios), dragon_psychic).
type(pokemon(kyogre), water).
type(pokemon(groudon), ground).
type(pokemon(rayquaza), dragon_flying).
type(pokemon(jirachi), steel_psychic).
type(pokemon(deoxys), psychic).
type(pokemon(turtwig), grass).
type(pokemon(grotle), grass).
type(pokemon(torterra), grass_ground).
type(pokemon(chimchar), fire).
type(pokemon(monferno), fire_fighting).
type(pokemon(infernape), fire_fighting).
type(pokemon(piplup), water).
type(pokemon(prinplup), water).
type(pokemon(empoleon), water_steel).
type(pokemon(starly), normal_flying).
type(pokemon(staravia), normal_flying).
type(pokemon(staraptor), normal_flying).
type(pokemon(bidoof), normal).
type(pokemon(bibarel), normal_water).
type(pokemon(kricketot), bug).
type(pokemon(kricketune), bug).
type(pokemon(shinx), electric).
type(pokemon(luxio), electric).
type(pokemon(luxray), electric).
type(pokemon(budew), grass_poison).
type(pokemon(roserade), grass_poison).
type(pokemon(cranidos), rock).
type(pokemon(rampardos), rock).
type(pokemon(shieldon), rock_steel).
type(pokemon(bastiodon), rock_steel).
type(pokemon(burmy), bug).
type(pokemon(wormadam), bug_grass).
type(pokemon(mothim), bug_flying).
type(pokemon(combee), bug_flying).
type(pokemon(vespiquen), bug_flying).
type(pokemon(pachirisu), electric).
type(pokemon(buizel), water).
type(pokemon(floatzel), water).
type(pokemon(cherubi), grass).
type(pokemon(cherrim), grass).
type(pokemon(shellos), water).
type(pokemon(gastrodon), water_ground).
type(pokemon(ambipom), normal).
type(pokemon(drifloon), ghost_flying).
type(pokemon(drifblim), ghost_flying).
type(pokemon(buneary), normal).
type(pokemon(lopunny), normal).
type(pokemon(mismagius), ghost).
type(pokemon(honchkrow), dark_flying).
type(pokemon(glameow), normal).
type(pokemon(purugly), normal).
type(pokemon(chingling), psychic).
type(pokemon(stunky), poison_dark).
type(pokemon(skuntank), poison_dark).
type(pokemon(bronzor), steel_psychic).
type(pokemon(bronzong), steel_psychic).
type(pokemon(bonsly), rock).
type(pokemon(mime_jr), psychic).
type(pokemon(happiny), normal).
type(pokemon(chatot), normal_flying).
type(pokemon(spiritomb), ghost_dark).
type(pokemon(gible), dragon_ground).
type(pokemon(gabite), dragon_ground).
type(pokemon(garchomp), dragon_ground).
type(pokemon(munchlax), normal).
type(pokemon(riolu), fighting).
type(pokemon(lucario), fighting_steel).
type(pokemon(hippopotas), ground).
type(pokemon(hippowdon), ground).
type(pokemon(skorupi), poison_bug).
type(pokemon(drapion), poison_dark).
type(pokemon(croagunk), poison_fighting).
type(pokemon(toxicroak), poison_fighting).
type(pokemon(carnivine), grass).
type(pokemon(finneon), water).
type(pokemon(lumineon), water).
type(pokemon(mantyke), water_flying).
type(pokemon(snover), ice_grass).
type(pokemon(abomasnow), ice_grass).
type(pokemon(weavile), dark_ice).
type(pokemon(magnezone), electric_steel).
type(pokemon(lickilicky), normal).
type(pokemon(rhyperior), ground_rock).
type(pokemon(tangrowth), grass).
type(pokemon(electivire), electric).
type(pokemon(magmortar), fire).
type(pokemon(togekiss), normal_flying).
type(pokemon(yanmega), bug_flying).
type(pokemon(leafeon), grass).
type(pokemon(glaceon), ice).
type(pokemon(gliscor), ground_flying).
type(pokemon(mamoswine), ice_ground).
type(pokemon(porygon_z), normal).
type(pokemon(gallade), psychic_fighting).
type(pokemon(probopass), rock_steel).
type(pokemon(dusknoir), ghost).
type(pokemon(froslass), ice_ghost).
type(pokemon(rotom), electric_ghost).
type(pokemon(uxie), psychic).
type(pokemon(mesprit), psychic).
type(pokemon(azelf), psychic).
type(pokemon(dialga), steel_dragon).
type(pokemon(palkia), water_dragon).
type(pokemon(heatran), fire_steel).
type(pokemon(regigigas), normal).
type(pokemon(giratina), ghost_dragon).
type(pokemon(cresselia), psychic).
type(pokemon(phione), water).
type(pokemon(manaphy), water).
type(pokemon(darkrai), dark).
type(pokemon(shaymin), grass).
type(pokemon(arceus), normal).
type(pokemon(victini), psychic_fire).
type(pokemon(snivy), grass).
type(pokemon(servine), grass).
type(pokemon(serperior), grass).
type(pokemon(tepig), fire).
type(pokemon(pignite), fire_fighting).
type(pokemon(emboar), fire_fighting).
type(pokemon(oshawott), water).
type(pokemon(dewott), water).
type(pokemon(samurott), water).
type(pokemon(patrat), normal).
type(pokemon(watchog), normal).
type(pokemon(lillipup), normal).
type(pokemon(herdier), normal).
type(pokemon(stoutland), normal).
type(pokemon(purrloin), dark).
type(pokemon(liepard), dark).
type(pokemon(pansage), grass).
type(pokemon(simisage), grass).
type(pokemon(pansear), fire).
type(pokemon(simisear), fire).
type(pokemon(panpour), water).
type(pokemon(simipour), water).
type(pokemon(munna), psychic).
type(pokemon(musharna), psychic).
type(pokemon(pidove), normal_flying).
type(pokemon(tranquill), normal_flying).
type(pokemon(unfezant), normal_flying).
type(pokemon(blitzle), electric).
type(pokemon(zebstrika), electric).
type(pokemon(roggenrola), rock).
type(pokemon(boldore), rock).
type(pokemon(gigalith), rock).
type(pokemon(woobat), psychic_flying).
type(pokemon(swoobat), psychic_flying).
type(pokemon(drilbur), ground).
type(pokemon(excadrill), ground_steel).
type(pokemon(audino), normal).
type(pokemon(timburr), fighting).
type(pokemon(gurdurr), fighting).
type(pokemon(conkeldurr), fighting).
type(pokemon(tympole), water).
type(pokemon(palpitoad), water_ground).
type(pokemon(seismitoad), water_ground).
type(pokemon(throh), fighting).
type(pokemon(sawk), fighting).
type(pokemon(sewaddle), bug_grass).
type(pokemon(swadloon), bug_grass).
type(pokemon(leavanny), bug_grass).
type(pokemon(venipede), bug_poison).
type(pokemon(whirlipede), bug_poison).
type(pokemon(scolipede), bug_poison).
type(pokemon(cottonee), grass).
type(pokemon(whimsicott), grass).
type(pokemon(petilil), grass).
type(pokemon(lilligant), grass).
type(pokemon(basculin), water).
type(pokemon(sandile), ground_dark).
type(pokemon(krokorok), ground_dark).
type(pokemon(krookodile), ground_dark).
type(pokemon(darumaka), fire).
type(pokemon(darmanitan), fire).
type(pokemon(maractus), grass).
type(pokemon(dwebble), bug_rock).
type(pokemon(crustle), bug_rock).
type(pokemon(scraggy), dark_fighting).
type(pokemon(scrafty), dark_fighting).
type(pokemon(sigilyph), psychic_flying).
type(pokemon(yamask), ghost).
type(pokemon(cofagrigus), ghost).
type(pokemon(tirtouga), water_rock).
type(pokemon(carracosta), water_rock).
type(pokemon(archen), rock_flying).
type(pokemon(archeops), rock_flying).
type(pokemon(trubbish), poison).
type(pokemon(garbodor), poison).
type(pokemon(zorua), dark).
type(pokemon(zoroark), dark).
type(pokemon(minccino), normal).
type(pokemon(ciccino), normal).
type(pokemon(gothita), psychic).
type(pokemon(gothorita), psychic).
type(pokemon(gothitelle), psychic).
type(pokemon(solosis), psychic).
type(pokemon(duosion), psychic).
type(pokemon(reuniclus), psychic).
type(pokemon(ducklett), water_flying).
type(pokemon(swanna), water_flying).
type(pokemon(vanillite), ice).
type(pokemon(vanillish), ice).
type(pokemon(vanilluxe), ice).
type(pokemon(deerling), normal_grass).
type(pokemon(sawsbuck), normal_grass).
type(pokemon(emolga), electric_flying).
type(pokemon(karrablast), bug).
type(pokemon(escavalier), bug_steel).
type(pokemon(foongus), grass_poison).
type(pokemon(amoonguss), grass_poison).
type(pokemon(frillish), water_ghost).
type(pokemon(jellicent), water_ghost).
type(pokemon(alomomola), water).
type(pokemon(joltik), bug_electric).
type(pokemon(galvantula), bug_electric).
type(pokemon(ferroseed), grass_steel).
type(pokemon(ferrothorn), grass_steel).
type(pokemon(klink), steel).
type(pokemon(klang), steel).
type(pokemon(klinklang), steel).
type(pokemon(tynamo), electric).
type(pokemon(eelektrik), electric).
type(pokemon(eelektross), electric).
type(pokemon(elgyem), psychic).
type(pokemon(beheeyem), psychic).
type(pokemon(litwick), ghost_fire).
type(pokemon(lampent), ghost_fire).
type(pokemon(chandelure), ghost_fire).
type(pokemon(axew), dragon).
type(pokemon(fraxure), dragon).
type(pokemon(haxorus), dragon).
type(pokemon(cubchoo), ice).
type(pokemon(beartic), ice).
type(pokemon(cryogonal), ice).
type(pokemon(shelmet), bug).
type(pokemon(accelgor), bug).
type(pokemon(stunfisk), ground_electric).
type(pokemon(mienfoo), fighting).
type(pokemon(mienshao), fighting).
type(pokemon(druddigon), dragon).
type(pokemon(golett), ground_ghost).
type(pokemon(golurk), ground_ghost).
type(pokemon(pawniard), dark_steel).
type(pokemon(bisharp), dark_steel).
type(pokemon(bouffalant), normal).
type(pokemon(rufflet), normal_flying).
type(pokemon(braviary), normal_flying).
type(pokemon(vullaby), dark_flying).
type(pokemon(mandibuzz), dark_flying).
type(pokemon(heatmor), fire).
type(pokemon(durant), bug_steel).
type(pokemon(deino), dark_dragon).
type(pokemon(zweilous), dark_dragon).
type(pokemon(hydreigon), dark_dragon).
type(pokemon(larvesta), bug_fire).
type(pokemon(volcarona), bug_fire).
type(pokemon(cobalion), steel_fighting).
type(pokemon(terrakion), rock_fighting).
type(pokemon(virizion), grass_fighting).
type(pokemon(tornadus), flying).
type(pokemon(thundurus), electric_flying).
type(pokemon(reshiram), dragon_fire).
type(pokemon(zekrom), dragon_electric).
type(pokemon(landorus), ground_flying).
type(pokemon(kyurem), dragon_ice).
type(pokemon(keldeo), water_fighting).
type(pokemon(meloetta), normal_psychic).
type(pokemon(genesect), bug_steel).
