attack_type(pokemon(bulbasaur), grass).
attack_type(pokemon(ivysaur), grass).
attack_type(pokemon(venusaur), grass).
attack_type(pokemon(charmander), fire).
attack_type(pokemon(charmeleon), fire).
attack_type(pokemon(charizard), fire).
attack_type(pokemon(squirtle), water).
attack_type(pokemon(wartortle), water).
attack_type(pokemon(blastoise), water).
attack_type(pokemon(caterpie), bug).
attack_type(pokemon(metapod), bug).
attack_type(pokemon(butterfree), bug).
attack_type(pokemon(weedle), bug).
attack_type(pokemon(kakuna), bug).
attack_type(pokemon(beedrill), bug).
attack_type(pokemon(pidgey), normal).
attack_type(pokemon(pidgeotto), normal).
attack_type(pokemon(pidgeot), normal).
attack_type(pokemon(rattata), normal).
attack_type(pokemon(raticate), normal).
attack_type(pokemon(spearow), normal).
attack_type(pokemon(fearow), normal).
attack_type(pokemon(ekans), poison).
attack_type(pokemon(arbok), poison).
attack_type(pokemon(pikachu), electric).
attack_type(pokemon(raichu), electric).
attack_type(pokemon(sandshrew), ground).
attack_type(pokemon(sandslash), ground).
attack_type(pokemon(nidoran), poison).
attack_type(pokemon(nidorina), poison).
attack_type(pokemon(nidoqueen), poison).
attack_type(pokemon(nidorino), poison).
attack_type(pokemon(nidoking), poison).
attack_type(pokemon(clefairy), normal).
attack_type(pokemon(clefable), normal).
attack_type(pokemon(vulpix), fire).
attack_type(pokemon(ninetales), fire).
attack_type(pokemon(jigglypuff), normal).
attack_type(pokemon(wigglytuff), normal).
attack_type(pokemon(zubat), poison).
attack_type(pokemon(golbat), poison).
attack_type(pokemon(oddish), grass).
attack_type(pokemon(gloom), grass).
attack_type(pokemon(vileplume), grass).
attack_type(pokemon(paras), bug).
attack_type(pokemon(parasect), bug).
attack_type(pokemon(venonat), bug).
attack_type(pokemon(venomoth), bug).
attack_type(pokemon(diglett), ground).
attack_type(pokemon(dugtrio), ground).
attack_type(pokemon(meowth), normal).
attack_type(pokemon(persian), normal).
attack_type(pokemon(psyduck), water).
attack_type(pokemon(golduck), water).
attack_type(pokemon(mankey), fighting).
attack_type(pokemon(primeape), fighting).
attack_type(pokemon(growlithe), fire).
attack_type(pokemon(arcanine), fire).
attack_type(pokemon(poliwag), water).
attack_type(pokemon(poliwhirl), water).
attack_type(pokemon(poliwrath), water).
attack_type(pokemon(abra), psychic).
attack_type(pokemon(kadabra), psychic).
attack_type(pokemon(alakazam), psychic).
attack_type(pokemon(machop), fighting).
attack_type(pokemon(machoke), fighting).
attack_type(pokemon(machamp), fighting).
attack_type(pokemon(bellsprout), grass).
attack_type(pokemon(weepinbell), grass).
attack_type(pokemon(victreebel), grass).
attack_type(pokemon(tentacool), water).
attack_type(pokemon(tentacruel), water).
attack_type(pokemon(geodude), rock).
attack_type(pokemon(graveler), rock).
attack_type(pokemon(golem), rock).
attack_type(pokemon(ponyta), fire).
attack_type(pokemon(rapidash), fire).
attack_type(pokemon(slowpoke), water).
attack_type(pokemon(slowbro), water).
attack_type(pokemon(magnemite), electric).
attack_type(pokemon(magneton), electric).
attack_type(pokemon(farfetchd), normal).
attack_type(pokemon(doduo), normal).
attack_type(pokemon(dodrio), normal).
attack_type(pokemon(seel), water).
attack_type(pokemon(dewgong), water).
attack_type(pokemon(grimer), poison).
attack_type(pokemon(muk), poison).
attack_type(pokemon(shellder), water).
attack_type(pokemon(cloyster), water).
attack_type(pokemon(gastly), ghost).
attack_type(pokemon(haunter), ghost).
attack_type(pokemon(gengar), ghost).
attack_type(pokemon(onix), rock).
attack_type(pokemon(drowzee), psychic).
attack_type(pokemon(hypno), psychic).
attack_type(pokemon(krabby), water).
attack_type(pokemon(kingler), water).
attack_type(pokemon(voltorb), electric).
attack_type(pokemon(electrode), electric).
attack_type(pokemon(exeggcute), grass).
attack_type(pokemon(exeggutor), grass).
attack_type(pokemon(cubone), ground).
attack_type(pokemon(marowak), ground).
attack_type(pokemon(hitmonlee), fighting).
attack_type(pokemon(hitmonchan), fighting).
attack_type(pokemon(lickitung), normal).
attack_type(pokemon(koffing), poison).
attack_type(pokemon(weezing), poison).
attack_type(pokemon(rhyhorn), ground).
attack_type(pokemon(rhydon), ground).
attack_type(pokemon(chansey), normal).
attack_type(pokemon(tangela), grass).
attack_type(pokemon(kangaskhan), normal).
attack_type(pokemon(horsea), water).
attack_type(pokemon(seadra), water).
attack_type(pokemon(goldeen), water).
attack_type(pokemon(seaking), water).
attack_type(pokemon(staryu), water).
attack_type(pokemon(starmie), water).
attack_type(pokemon(mr-mime), psychic).
attack_type(pokemon(scyther), bug).
attack_type(pokemon(jynx), ice).
attack_type(pokemon(electabuzz), electric).
attack_type(pokemon(magmar), fire).
attack_type(pokemon(pinsir), bug).
attack_type(pokemon(tauros), normal).
attack_type(pokemon(magikarp), water).
attack_type(pokemon(gyarados), water).
attack_type(pokemon(lapras), water).
attack_type(pokemon(ditto), normal).
attack_type(pokemon(eevee), normal).
attack_type(pokemon(vaporeon), water).
attack_type(pokemon(jolteon), electric).
attack_type(pokemon(flareon), fire).
attack_type(pokemon(porygon), normal).
attack_type(pokemon(omanyte), rock).
attack_type(pokemon(omastar), rock).
attack_type(pokemon(kabuto), rock).
attack_type(pokemon(kabutops), rock).
attack_type(pokemon(aerodactyl), rock).
attack_type(pokemon(snorlax), normal).
attack_type(pokemon(articuno), ice).
attack_type(pokemon(zapdos), electric).
attack_type(pokemon(moltres), fire).
attack_type(pokemon(dratini), dragon).
attack_type(pokemon(dragonair), dragon).
attack_type(pokemon(dragonite), dragon).
attack_type(pokemon(mewtwo), psychic).
attack_type(pokemon(mew), psychic).
attack_type(pokemon(chikorita), grass).
attack_type(pokemon(bayleef), grass).
attack_type(pokemon(meganium), grass).
attack_type(pokemon(cyndaquil), fire).
attack_type(pokemon(quilava), fire).
attack_type(pokemon(typhlosion), fire).
attack_type(pokemon(totodile), water).
attack_type(pokemon(croconaw), water).
attack_type(pokemon(feraligatr), water).
attack_type(pokemon(sentret), normal).
attack_type(pokemon(furret), normal).
attack_type(pokemon(hoothoot), normal).
attack_type(pokemon(noctowl), normal).
attack_type(pokemon(ledyba), bug).
attack_type(pokemon(ledian), bug).
attack_type(pokemon(spinarak), bug).
attack_type(pokemon(ariados), bug).
attack_type(pokemon(crobat), poison).
attack_type(pokemon(chinchou), water).
attack_type(pokemon(lanturn), water).
attack_type(pokemon(pichu), electric).
attack_type(pokemon(cleffa), normal).
attack_type(pokemon(igglybuff), normal).
attack_type(pokemon(togepi), normal).
attack_type(pokemon(togetic), normal).
attack_type(pokemon(natu), psychic).
attack_type(pokemon(xatu), psychic).
attack_type(pokemon(mareep), electric).
attack_type(pokemon(flaaffy), electric).
attack_type(pokemon(ampharos), electric).
attack_type(pokemon(bellossom), grass).
attack_type(pokemon(marill), water).
attack_type(pokemon(azumarill), water).
attack_type(pokemon(sudowoodo), rock).
attack_type(pokemon(politoed), water).
attack_type(pokemon(hoppip), grass).
attack_type(pokemon(skiploom), grass).
attack_type(pokemon(jumpluff), grass).
attack_type(pokemon(aipom), normal).
attack_type(pokemon(sunkern), grass).
attack_type(pokemon(sunflora), grass).
attack_type(pokemon(yanma), bug).
attack_type(pokemon(wooper), water).
attack_type(pokemon(quagsire), water).
attack_type(pokemon(espeon), psychic).
attack_type(pokemon(umbreon), dark).
attack_type(pokemon(murkrow), dark).
attack_type(pokemon(slowking), water).
attack_type(pokemon(misdreavus), ghost).
attack_type(pokemon(unown), psychic).
attack_type(pokemon(wobbuffet), psychic).
attack_type(pokemon(girafarig), normal).
attack_type(pokemon(pineco), bug).
attack_type(pokemon(forretress), bug).
attack_type(pokemon(dunsparce), normal).
attack_type(pokemon(gligar), ground).
attack_type(pokemon(steelix), steel).
attack_type(pokemon(snubbull), normal).
attack_type(pokemon(granbull), normal).
attack_type(pokemon(qwilfish), water).
attack_type(pokemon(scizor), bug).
attack_type(pokemon(shuckle), bug).
attack_type(pokemon(heracross), bug).
attack_type(pokemon(sneasel), dark).
attack_type(pokemon(teddiursa), normal).
attack_type(pokemon(ursaring), normal).
attack_type(pokemon(slugma), fire).
attack_type(pokemon(magcargo), fire).
attack_type(pokemon(swinub), ice).
attack_type(pokemon(piloswine), ice).
attack_type(pokemon(corsola), water).
attack_type(pokemon(remoraid), water).
attack_type(pokemon(octillery), water).
attack_type(pokemon(delibird), ice).
attack_type(pokemon(mantine), water).
attack_type(pokemon(skarmory), steel).
attack_type(pokemon(houndour), dark).
attack_type(pokemon(houndoom), dark).
attack_type(pokemon(kingdra), water).
attack_type(pokemon(phanpy), ground).
attack_type(pokemon(donphan), ground).
attack_type(pokemon(porygon2), normal).
attack_type(pokemon(stantler), normal).
attack_type(pokemon(smeargle), normal).
attack_type(pokemon(tyrogue), fighting).
attack_type(pokemon(hitmontop), fighting).
attack_type(pokemon(smoochum), ice).
attack_type(pokemon(elekid), electric).
attack_type(pokemon(magby), fire).
attack_type(pokemon(miltank), normal).
attack_type(pokemon(blissey), normal).
attack_type(pokemon(raikou), electric).
attack_type(pokemon(entei), fire).
attack_type(pokemon(suicune), water).
attack_type(pokemon(larvitar), rock).
attack_type(pokemon(pupitar), rock).
attack_type(pokemon(tyranitar), rock).
attack_type(pokemon(lugia), psychic).
attack_type(pokemon(ho-oh), fire).
attack_type(pokemon(celebi), psychic).
attack_type(pokemon(treecko), grass).
attack_type(pokemon(grovyle), grass).
attack_type(pokemon(sceptile), grass).
attack_type(pokemon(torchic), fire).
attack_type(pokemon(combusken), fire).
attack_type(pokemon(blaziken), fire).
attack_type(pokemon(mudkip), water).
attack_type(pokemon(marshtomp), water).
attack_type(pokemon(swampert), water).
attack_type(pokemon(poochyena), dark).
attack_type(pokemon(mightyena), dark).
attack_type(pokemon(zigzagoon), normal).
attack_type(pokemon(linoone), normal).
attack_type(pokemon(wurmple), bug).
attack_type(pokemon(silcoon), bug).
attack_type(pokemon(beautifly), bug).
attack_type(pokemon(cascoon), bug).
attack_type(pokemon(dustox), bug).
attack_type(pokemon(lotad), water).
attack_type(pokemon(lombre), water).
attack_type(pokemon(ludicolo), water).
attack_type(pokemon(seedot), grass).
attack_type(pokemon(nuzleaf), grass).
attack_type(pokemon(shiftry), grass).
attack_type(pokemon(taillow), normal).
attack_type(pokemon(swellow), normal).
attack_type(pokemon(wingull), water).
attack_type(pokemon(pelipper), water).
attack_type(pokemon(ralts), psychic).
attack_type(pokemon(kirlia), psychic).
attack_type(pokemon(gardevoir), psychic).
attack_type(pokemon(surskit), bug).
attack_type(pokemon(masquerain), bug).
attack_type(pokemon(shroomish), grass).
attack_type(pokemon(breloom), grass).
attack_type(pokemon(slakoth), normal).
attack_type(pokemon(vigoroth), normal).
attack_type(pokemon(slaking), normal).
attack_type(pokemon(nincada), bug).
attack_type(pokemon(ninjask), bug).
attack_type(pokemon(shedinja), bug).
attack_type(pokemon(whismur), normal).
attack_type(pokemon(loudred), normal).
attack_type(pokemon(exploud), normal).
attack_type(pokemon(makuhita), fighting).
attack_type(pokemon(hariyama), fighting).
attack_type(pokemon(azurill), normal).
attack_type(pokemon(nosepass), rock).
attack_type(pokemon(skitty), normal).
attack_type(pokemon(delcatty), normal).
attack_type(pokemon(sableye), dark).
attack_type(pokemon(mawile), steel).
attack_type(pokemon(aron), steel).
attack_type(pokemon(lairon), steel).
attack_type(pokemon(aggron), steel).
attack_type(pokemon(meditite), fighting).
attack_type(pokemon(medicham), fighting).
attack_type(pokemon(electrike), electric).
attack_type(pokemon(manectric), electric).
attack_type(pokemon(plusle), electric).
attack_type(pokemon(minun), electric).
attack_type(pokemon(volbeat), bug).
attack_type(pokemon(illumise), bug).
attack_type(pokemon(roselia), grass).
attack_type(pokemon(gulpin), poison).
attack_type(pokemon(swalot), poison).
attack_type(pokemon(carvanha), water).
attack_type(pokemon(sharpedo), water).
attack_type(pokemon(wailmer), water).
attack_type(pokemon(wailord), water).
attack_type(pokemon(numel), fire).
attack_type(pokemon(camerupt), fire).
attack_type(pokemon(torkoal), fire).
attack_type(pokemon(spoink), psychic).
attack_type(pokemon(grumpig), psychic).
attack_type(pokemon(spinda), normal).
attack_type(pokemon(trapinch), ground).
attack_type(pokemon(vibrava), ground).
attack_type(pokemon(flygon), ground).
attack_type(pokemon(cacnea), grass).
attack_type(pokemon(cacturne), grass).
attack_type(pokemon(swablu), normal).
attack_type(pokemon(altaria), dragon).
attack_type(pokemon(zangoose), normal).
attack_type(pokemon(seviper), poison).
attack_type(pokemon(lunatone), rock).
attack_type(pokemon(solrock), rock).
attack_type(pokemon(barboach), water).
attack_type(pokemon(whiscash), water).
attack_type(pokemon(corphish), water).
attack_type(pokemon(crawdaunt), water).
attack_type(pokemon(baltoy), ground).
attack_type(pokemon(claydol), ground).
attack_type(pokemon(lileep), rock).
attack_type(pokemon(cradily), rock).
attack_type(pokemon(anorith), rock).
attack_type(pokemon(armaldo), rock).
attack_type(pokemon(feebas), water).
attack_type(pokemon(milotic), water).
attack_type(pokemon(castform), normal).
attack_type(pokemon(kecleon), normal).
attack_type(pokemon(shuppet), ghost).
attack_type(pokemon(banette), ghost).
attack_type(pokemon(duskull), ghost).
attack_type(pokemon(dusclops), ghost).
attack_type(pokemon(tropius), grass).
attack_type(pokemon(chimecho), psychic).
attack_type(pokemon(absol), dark).
attack_type(pokemon(wynaut), psychic).
attack_type(pokemon(snorunt), ice).
attack_type(pokemon(glalie), ice).
attack_type(pokemon(spheal), ice).
attack_type(pokemon(sealeo), ice).
attack_type(pokemon(walrein), ice).
attack_type(pokemon(clamperl), water).
attack_type(pokemon(huntail), water).
attack_type(pokemon(gorebyss), water).
attack_type(pokemon(relicanth), water).
attack_type(pokemon(luvdisc), water).
attack_type(pokemon(bagon), dragon).
attack_type(pokemon(shelgon), dragon).
attack_type(pokemon(salamence), dragon).
attack_type(pokemon(beldum), steel).
attack_type(pokemon(metang), steel).
attack_type(pokemon(metagross), steel).
attack_type(pokemon(regirock), rock).
attack_type(pokemon(regice), ice).
attack_type(pokemon(registeel), steel).
attack_type(pokemon(latias), dragon).
attack_type(pokemon(latios), dragon).
attack_type(pokemon(kyogre), water).
attack_type(pokemon(groudon), ground).
attack_type(pokemon(rayquaza), dragon).
attack_type(pokemon(jirachi), steel).
attack_type(pokemon(deoxys), psychic).
attack_type(pokemon(turtwig), grass).
attack_type(pokemon(grotle), grass).
attack_type(pokemon(torterra), grass).
attack_type(pokemon(chimchar), fire).
attack_type(pokemon(monferno), fire).
attack_type(pokemon(infernape), fire).
attack_type(pokemon(piplup), water).
attack_type(pokemon(prinplup), water).
attack_type(pokemon(empoleon), water).
attack_type(pokemon(starly), normal).
attack_type(pokemon(staravia), normal).
attack_type(pokemon(staraptor), normal).
attack_type(pokemon(bidoof), normal).
attack_type(pokemon(bibarel), normal).
attack_type(pokemon(kricketot), bug).
attack_type(pokemon(kricketune), bug).
attack_type(pokemon(shinx), electric).
attack_type(pokemon(luxio), electric).
attack_type(pokemon(luxray), electric).
attack_type(pokemon(budew), grass).
attack_type(pokemon(roserade), grass).
attack_type(pokemon(cranidos), rock).
attack_type(pokemon(rampardos), rock).
attack_type(pokemon(shieldon), rock).
attack_type(pokemon(bastiodon), rock).
attack_type(pokemon(burmy), bug).
attack_type(pokemon(wormadam), bug).
attack_type(pokemon(mothim), bug).
attack_type(pokemon(combee), bug).
attack_type(pokemon(vespiquen), bug).
attack_type(pokemon(pachirisu), electric).
attack_type(pokemon(buizel), water).
attack_type(pokemon(floatzel), water).
attack_type(pokemon(cherubi), grass).
attack_type(pokemon(cherrim), grass).
attack_type(pokemon(shellos), water).
attack_type(pokemon(gastrodon), water).
attack_type(pokemon(ambipom), normal).
attack_type(pokemon(drifloon), ghost).
attack_type(pokemon(drifblim), ghost).
attack_type(pokemon(buneary), normal).
attack_type(pokemon(lopunny), normal).
attack_type(pokemon(mismagius), ghost).
attack_type(pokemon(honchkrow), dark).
attack_type(pokemon(glameow), normal).
attack_type(pokemon(purugly), normal).
attack_type(pokemon(chingling), psychic).
attack_type(pokemon(stunky), poison).
attack_type(pokemon(skuntank), poison).
attack_type(pokemon(bronzor), steel).
attack_type(pokemon(bronzong), steel).
attack_type(pokemon(bonsly), rock).
attack_type(pokemon(mime-jr), psychic).
attack_type(pokemon(happiny), normal).
attack_type(pokemon(chatot), normal).
attack_type(pokemon(spiritomb), ghost).
attack_type(pokemon(gible), dragon).
attack_type(pokemon(gabite), dragon).
attack_type(pokemon(garchomp), dragon).
attack_type(pokemon(munchlax), normal).
attack_type(pokemon(riolu), fighting).
attack_type(pokemon(lucario), fighting).
attack_type(pokemon(hippopotas), ground).
attack_type(pokemon(hippowdon), ground).
attack_type(pokemon(skorupi), poison).
attack_type(pokemon(drapion), poison).
attack_type(pokemon(croagunk), poison).
attack_type(pokemon(toxicroak), poison).
attack_type(pokemon(carnivine), grass).
attack_type(pokemon(finneon), water).
attack_type(pokemon(lumineon), water).
attack_type(pokemon(mantyke), water).
attack_type(pokemon(snover), ice).
attack_type(pokemon(abomasnow), ice).
attack_type(pokemon(weavile), dark).
attack_type(pokemon(magnezone), electric).
attack_type(pokemon(lickilicky), normal).
attack_type(pokemon(rhyperior), ground).
attack_type(pokemon(tangrowth), grass).
attack_type(pokemon(electivire), electric).
attack_type(pokemon(magmortar), fire).
attack_type(pokemon(togekiss), normal).
attack_type(pokemon(yanmega), bug).
attack_type(pokemon(leafeon), grass).
attack_type(pokemon(glaceon), ice).
attack_type(pokemon(gliscor), ground).
attack_type(pokemon(mamoswine), ice).
attack_type(pokemon(porygon-z), normal).
attack_type(pokemon(gallade), psychic).
attack_type(pokemon(probopass), rock).
attack_type(pokemon(dusknoir), ghost).
attack_type(pokemon(froslass), ice).
attack_type(pokemon(rotom), electric).
attack_type(pokemon(uxie), psychic).
attack_type(pokemon(mesprit), psychic).
attack_type(pokemon(azelf), psychic).
attack_type(pokemon(dialga), steel).
attack_type(pokemon(palkia), water).
attack_type(pokemon(heatran), fire).
attack_type(pokemon(regigigas), normal).
attack_type(pokemon(giratina), ghost).
attack_type(pokemon(cresselia), psychic).
attack_type(pokemon(phione), water).
attack_type(pokemon(manaphy), water).
attack_type(pokemon(darkrai), dark).
attack_type(pokemon(shaymin), grass).
attack_type(pokemon(arceus), normal).
attack_type(pokemon(victini), psychic).
attack_type(pokemon(snivy), grass).
attack_type(pokemon(servine), grass).
attack_type(pokemon(serperior), grass).
attack_type(pokemon(tepig), fire).
attack_type(pokemon(pignite), fire).
attack_type(pokemon(emboar), fire).
attack_type(pokemon(oshawott), water).
attack_type(pokemon(dewott), water).
attack_type(pokemon(samurott), water).
attack_type(pokemon(patrat), normal).
attack_type(pokemon(watchog), normal).
attack_type(pokemon(lillipup), normal).
attack_type(pokemon(herdier), normal).
attack_type(pokemon(stoutland), normal).
attack_type(pokemon(purrloin), dark).
attack_type(pokemon(liepard), dark).
attack_type(pokemon(pansage), grass).
attack_type(pokemon(simisage), grass).
attack_type(pokemon(pansear), fire).
attack_type(pokemon(simisear), fire).
attack_type(pokemon(panpour), water).
attack_type(pokemon(simipour), water).
attack_type(pokemon(munna), psychic).
attack_type(pokemon(musharna), psychic).
attack_type(pokemon(pidove), normal).
attack_type(pokemon(tranquill), normal).
attack_type(pokemon(unfezant), normal).
attack_type(pokemon(blitzle), electric).
attack_type(pokemon(zebstrika), electric).
attack_type(pokemon(roggenrola), rock).
attack_type(pokemon(boldore), rock).
attack_type(pokemon(gigalith), rock).
attack_type(pokemon(woobat), psychic).
attack_type(pokemon(swoobat), psychic).
attack_type(pokemon(drilbur), ground).
attack_type(pokemon(excadrill), ground).
attack_type(pokemon(audino), normal).
attack_type(pokemon(timburr), fighting).
attack_type(pokemon(gurdurr), fighting).
attack_type(pokemon(conkeldurr), fighting).
attack_type(pokemon(tympole), water).
attack_type(pokemon(palpitoad), water).
attack_type(pokemon(seismitoad), water).
attack_type(pokemon(throh), fighting).
attack_type(pokemon(sawk), fighting).
attack_type(pokemon(sewaddle), bug).
attack_type(pokemon(swadloon), bug).
attack_type(pokemon(leavanny), bug).
attack_type(pokemon(venipede), bug).
attack_type(pokemon(whirlipede), bug).
attack_type(pokemon(scolipede), bug).
attack_type(pokemon(cottonee), grass).
attack_type(pokemon(whimsicott), grass).
attack_type(pokemon(petilil), grass).
attack_type(pokemon(lilligant), grass).
attack_type(pokemon(basculin), water).
attack_type(pokemon(sandile), ground).
attack_type(pokemon(krokorok), ground).
attack_type(pokemon(krookodile), ground).
attack_type(pokemon(darumaka), fire).
attack_type(pokemon(darmanitan), fire).
attack_type(pokemon(maractus), grass).
attack_type(pokemon(dwebble), bug).
attack_type(pokemon(crustle), bug).
attack_type(pokemon(scraggy), dark).
attack_type(pokemon(scrafty), dark).
attack_type(pokemon(sigilyph), psychic).
attack_type(pokemon(yamask), ghost).
attack_type(pokemon(cofagrigus), ghost).
attack_type(pokemon(tirtouga), water).
attack_type(pokemon(carracosta), water).
attack_type(pokemon(archen), rock).
attack_type(pokemon(archeops), rock).
attack_type(pokemon(trubbish), poison).
attack_type(pokemon(garbodor), poison).
attack_type(pokemon(zorua), dark).
attack_type(pokemon(zoroark), dark).
attack_type(pokemon(minccino), normal).
attack_type(pokemon(ciccino), normal).
attack_type(pokemon(gothita), psychic).
attack_type(pokemon(gothorita), psychic).
attack_type(pokemon(gothitelle), psychic).
attack_type(pokemon(solosis), psychic).
attack_type(pokemon(duosion), psychic).
attack_type(pokemon(reuniclus), psychic).
attack_type(pokemon(ducklett), water).
attack_type(pokemon(swanna), water).
attack_type(pokemon(vanillite), ice).
attack_type(pokemon(vanillish), ice).
attack_type(pokemon(vanilluxe), ice).
attack_type(pokemon(deerling), normal).
attack_type(pokemon(sawsbuck), normal).
attack_type(pokemon(emolga), electric).
attack_type(pokemon(karrablast), bug).
attack_type(pokemon(escavalier), bug).
attack_type(pokemon(foongus), grass).
attack_type(pokemon(amoonguss), grass).
attack_type(pokemon(frillish), water).
attack_type(pokemon(jellicent), water).
attack_type(pokemon(alomomola), water).
attack_type(pokemon(joltik), bug).
attack_type(pokemon(galvantula), bug).
attack_type(pokemon(ferroseed), grass).
attack_type(pokemon(ferrothorn), grass).
attack_type(pokemon(klink), steel).
attack_type(pokemon(klang), steel).
attack_type(pokemon(klinklang), steel).
attack_type(pokemon(tynamo), electric).
attack_type(pokemon(eelektrik), electric).
attack_type(pokemon(eelektross), electric).
attack_type(pokemon(elgyem), psychic).
attack_type(pokemon(beheeyem), psychic).
attack_type(pokemon(litwick), ghost).
attack_type(pokemon(lampent), ghost).
attack_type(pokemon(chandelure), ghost).
attack_type(pokemon(axew), dragon).
attack_type(pokemon(fraxure), dragon).
attack_type(pokemon(haxorus), dragon).
attack_type(pokemon(cubchoo), ice).
attack_type(pokemon(beartic), ice).
attack_type(pokemon(cryogonal), ice).
attack_type(pokemon(shelmet), bug).
attack_type(pokemon(accelgor), bug).
attack_type(pokemon(stunfisk), ground).
attack_type(pokemon(mienfoo), fighting).
attack_type(pokemon(mienshao), fighting).
attack_type(pokemon(druddigon), dragon).
attack_type(pokemon(golett), ground).
attack_type(pokemon(golurk), ground).
attack_type(pokemon(pawniard), dark).
attack_type(pokemon(bisharp), dark).
attack_type(pokemon(bouffalant), normal).
attack_type(pokemon(rufflet), normal).
attack_type(pokemon(braviary), normal).
attack_type(pokemon(vullaby), dark).
attack_type(pokemon(mandibuzz), dark).
attack_type(pokemon(heatmor), fire).
attack_type(pokemon(durant), bug).
attack_type(pokemon(deino), dark).
attack_type(pokemon(zweilous), dark).
attack_type(pokemon(hydreigon), dark).
attack_type(pokemon(larvesta), bug).
attack_type(pokemon(volcarona), bug).
attack_type(pokemon(cobalion), steel).
attack_type(pokemon(terrakion), rock).
attack_type(pokemon(virizion), grass).
attack_type(pokemon(tornadus), flying).
attack_type(pokemon(thundurus), electric).
attack_type(pokemon(reshiram), dragon).
attack_type(pokemon(zekrom), dragon).
attack_type(pokemon(landorus), ground).
attack_type(pokemon(kyurem), dragon).
attack_type(pokemon(keldeo), water).
attack_type(pokemon(meloetta), normal).
attack_type(pokemon(genesect), bug).
