evolve_from(ivysaur,bulbasaur).
evolve_from(venusaur,ivysaur).
evolve_from(charmeleon,charmander).
evolve_from(charizard,charmeleon).
evolve_from(wartortle,squirtle).
evolve_from(blastoise,wartortle).
evolve_from(metapod,caterpie).
evolve_from(butterfree,metapod).
evolve_from(kakuna,weedle).
evolve_from(beedrill,kakuna).
evolve_from(pidgeotto,pidgey).
evolve_from(pidgeot,pidgeotto).
evolve_from(raticate,rattata).
evolve_from(fearow,spearow).
evolve_from(arbok,ekans).
evolve_from(pikachu,pichu).
evolve_from(raichu,pikachu).
evolve_from(sandslash,sandshrew).
evolve_from(nidorina,nidoran (♀)).
evolve_from(nidoqueen,nidorina).
evolve_from(nidorino,nidoran (♂)).
evolve_from(nidoking,nidorino).
evolve_from(clefairy,cleffa).
evolve_from(clefable,clefairy).
evolve_from(ninetales,vulpix).
evolve_from(jigglypuff,igglybuff).
evolve_from(wigglytuff,jigglypuff).
evolve_from(golbat,zubat).
evolve_from(gloom,oddish).
evolve_from(vileplume,gloom).
evolve_from(parasect,paras).
evolve_from(venomoth,venonat).
evolve_from(dugtrio,diglett).
evolve_from(persian,meowth).
evolve_from(golduck,psyduck).
evolve_from(primeape,mankey).
evolve_from(arcanine,growlithe).
evolve_from(poliwhirl,poliwag).
evolve_from(poliwrath,poliwhirl).
evolve_from(kadabra,kadabra).
evolve_from(alakazam,alakazam).
evolve_from(machoke,machop).
evolve_from(machamp,machoke).
evolve_from(weepinbell,bellsprout).
evolve_from(victreebel,weepinbell).
evolve_from(tentacruel,tentacool).
evolve_from(graveler,geodude).
evolve_from(golem,graveller).
evolve_from(rapidash,ponyta).
evolve_from(slowbro,slowpoke).
evolve_from(magneton,magnemite).
evolve_from(dodrio,doduo).
evolve_from(dewgong,seel).
evolve_from(muk,grimer).
evolve_from(cloyster,shellder).
evolve_from(haunter,gastly).
evolve_from(gengar,haunter).
evolve_from(hypno,drowzee).
evolve_from(kingler,krabby).
evolve_from(electrode,voltorb).
evolve_from(exeggutor,exeggcute).
evolve_from(marowak,cubone).
evolve_from(hitmonlee,tyrogue).
evolve_from(hitmonchan,tyrogue).
evolve_from(weezing,koffing).
evolve_from(rhydon,rhyhorn).
evolve_from(chansey,happiny).
evolve_from(seadra,horsea).
evolve_from(seaking,goldeen).
evolve_from(starmie,staryu).
evolve_from(mr. mime,mime jr.).
evolve_from(jynx,smoochum).
evolve_from(gyarados,magikarp).
evolve_from(vaporeon,eevee).
evolve_from(jolteon,eevee).
evolve_from(flareon,eevee).
evolve_from(omastar,omanyte).
evolve_from(kabutops,kabuto).
evolve_from(snorlax,munchlax).
evolve_from(dragonair,dratini).
evolve_from(dragonite,dragonair).
evolve_from(bayleef,chikorita).
evolve_from(meganium,bayleaf).
evolve_from(quilava,cyndaquil).
evolve_from(typhlosion,quilava).
evolve_from(croconaw,totodile).
evolve_from(feraligatr,croconaw).
evolve_from(furret,sentret).
evolve_from(noctowl,hoothoot).
evolve_from(ledian,ledyba).
evolve_from(ariados,spinarak).
evolve_from(crobat,golbat).
evolve_from(lanturn,chinchou).
evolve_from(togetic,togepi).
evolve_from(xatu,natu).
evolve_from(flaaffy,mareep).
evolve_from(ampharos,flaafy).
evolve_from(bellossom,gloom).
evolve_from(marill,azurill).
evolve_from(azumarill,marill).
evolve_from(sudowoodo,bonsly).
evolve_from(politoed,polywhirl).
evolve_from(skiploom,hoppip).
evolve_from(jumpluff,skiploom).
evolve_from(sunflora,sunkern).
evolve_from(quagsire,wooper).
evolve_from(espeon,eevee).
evolve_from(umbreon,eevee).
evolve_from(slowking,slowbro).
evolve_from(wobbuffet,wynaut).
evolve_from(forretress,pineco).
evolve_from(steelix,onix).
evolve_from(granbull,snubbull).
evolve_from(scizor,scyther).
evolve_from(ursaring,teddiursa).
evolve_from(magcargo,slugma).
evolve_from(piloswine,swinub).
evolve_from(octillery,remoraid).
evolve_from(mantine,mantyke).
evolve_from(houndoom,houndour).
evolve_from(kingdra,seadra).
evolve_from(donphan,phanphy).
evolve_from(porygon2,porygon).
evolve_from(hitmontop,tyrogue).
evolve_from(blissey,chansey).
evolve_from(pupitar,larvitar).
evolve_from(tyranitar,pupitar).
evolve_from(grovyle,treecko).
evolve_from(sceptile,grovyle).
evolve_from(combusken,torchic).
evolve_from(blaziken,combusken).
evolve_from(marshtomp,mudkip).
evolve_from(swampert,marshtomp).
evolve_from(mightyena,poochyena).
evolve_from(linoone,zigzagoon).
evolve_from(silcoon,wurmple).
evolve_from(beautifly,silcoon).
evolve_from(cascoon,wurmple).
evolve_from(dustox,cascoon).
evolve_from(lombre,lotad).
evolve_from(ludicolo,lombre).
evolve_from(nuzleaf,seedot).
evolve_from(shiftry,nuzleaf).
evolve_from(swellow,taillow).
evolve_from(pelipper,wingull).
evolve_from(kirlia,ralts).
evolve_from(gardevoir,kirlia).
evolve_from(masquerain,surskit).
evolve_from(breloom,shroomish).
evolve_from(vigoroth,slakoth).
evolve_from(slaking,vigoroth).
evolve_from(ninjask,nincada).
evolve_from(shedinja,nincada).
evolve_from(loudred,whismur).
evolve_from(exploud,loudred).
evolve_from(hariyama,makuhita).
evolve_from(delcatty,skitty).
evolve_from(lairon,aron).
evolve_from(aggron,lairon).
evolve_from(medicham,meditite).
evolve_from(manectric,electrike).
evolve_from(roselia,budew).
evolve_from(swalot,gulpin).
evolve_from(sharpedo,carvahna).
evolve_from(wailord,wailmer).
evolve_from(camerupt,numel).
evolve_from(vibrava,trapinch).
evolve_from(flygon,vibrava).
evolve_from(cacturne,cacnea).
evolve_from(altaria,swablu).
evolve_from(whiscash,barboach).
evolve_from(crawdaunt,corphish).
evolve_from(claydol,baltoy).
evolve_from(cradily,lileep).
evolve_from(armaldo,anorith).
evolve_from(milotic,feebas).
evolve_from(banette,shuppet).
evolve_from(dusclops,duskull).
evolve_from(chimecho,chingling).
evolve_from(glalie,snorunt).
evolve_from(sealeo,spheal).
evolve_from(walrein,sealeo).
evolve_from(huntail,clampearl).
evolve_from(gorebyss,clampearl).
evolve_from(shelgon,bagon).
evolve_from(salamence,shelgon).
evolve_from(metang,beldum).
evolve_from(metagross,metang).
evolve_from(grotle,turtwig).
evolve_from(torterra,grotle).
evolve_from(monferno,chimchar).
evolve_from(infernape,monferno).
evolve_from(prinplup,piplup).
evolve_from(empoleon,prinplup).
evolve_from(staravia,starly).
evolve_from(staraptor,staravia).
evolve_from(bibarel,bidoof).
evolve_from(kricketune,kricketot).
evolve_from(luxio,shinx).
evolve_from(luxray,luxio).
evolve_from(roserade,roselia).
evolve_from(rampardos,cranidos).
evolve_from(bastiodon,shiledon).
evolve_from(wormadam (p),burmy).
evolve_from(wormadam (s),burmy).
evolve_from(wormadam (t),burmy).
evolve_from(mothim,burmy).
evolve_from(vespiquen,combee).
evolve_from(floatzel,buizel).
evolve_from(cherrim,cherubi).
evolve_from(gastrodon,shellos).
evolve_from(ambipom,aipom).
evolve_from(drifblim,drifloon).
evolve_from(lopunny,buneary).
evolve_from(honchkrow,murkrow).
evolve_from(purugly,glameow).
evolve_from(skuntank,stunky).
evolve_from(bronzong,bronzor).
evolve_from(gabite,gible).
evolve_from(garchomp,gabite).
evolve_from(lucario,riolu).
evolve_from(hippowdon,hippopotas).
evolve_from(drapion,skorupi).
evolve_from(toxicroak,croagunk).
evolve_from(lumineon,finneon).
evolve_from(abomasnow,snover).
evolve_from(magnezone,magneton).
evolve_from(lickilicky,lickitung).
evolve_from(rhyperior,rhydon).
evolve_from(tangrowth,tangela).
evolve_from(electivire,electabuzz).
evolve_from(magmortar,magneton).
evolve_from(togekiss,togetic).
evolve_from(yanmega,yanma).
evolve_from(leafeon,eevee).
evolve_from(glaceon,eevee).
evolve_from(gliscor,gligar).
evolve_from(mamoswine,piloswine).
evolve_from(porygon-z,porygon).
evolve_from(gallade,kirlia).
evolve_from(probopass,nosepass).
evolve_from(dusknoir,dusclops).
evolve_from(froslass,snorunt).
